name: Manual
on:
  workflow_dispatch:  # 手動実行イベント
    inputs:
      greeting: # 入力パラメータ名
        type: string    # 型
        default: Hello  # デフォルト値
        required: true  # 必須フラグ
        description: A cheerful word  # 概要
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
        required: true
        default: info
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"  # 入力パラメータ「greeting」の参照    
